name: bitfit

services:
  server:
    container_name: server
    build:
      context: .
      dockerfile: ./app/Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - bitfit_network
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    env_file:
      - .env
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./utils/db:/docker-entrypoint-initdb.d
    networks:
      - bitfit_network

volumes:
  mongo_data:
    driver: local

networks:
  bitfit_network:
    driver: bridge
