name: bitfit

services:
  server:
    container_name: server
    build:
      context: .
      dockerfile: ./app/Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - bitfit_network
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    env_file:
      - .env
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./utils/db:/docker-entrypoint-initdb.d
    networks:
      - bitfit_network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    env_file:
      - .env
    volumes:
      - rabbit_data:/var/lib/rabbitmq/
      - rabbit_logs:/var/log/rabbitmq
    networks:
      - bad_inc_net
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongo_data:
    driver: local
  rabbit_data:
  rabbit_logs:

networks:
  bitfit_network:
    driver: bridge
